import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { Keypair, type PublicKey } from "@solana/web3.js";

const ANCHOR_TOML = "Anchor.toml";

function parseProgramNamesFromToml(contents: string): string[] {
  const names: string[] = [];
  let inPrograms = false;
  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (line.startsWith("[")) {
      inPrograms = /^\[programs\.[^\]]+\]$/.test(line);
      continue;
    }
    if (!inPrograms || line.length === 0 || line.startsWith("#")) continue;
    const match = line.match(/^["']?([A-Za-z0-9_-]+)["']?\s*=/);
    if (match) names.push(match[1]);
  }
  return names;
}

function programDirs(cwd: string): string[] {
  const dir = join(cwd, "programs");
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter((name) => {
    try {
      return (
        statSync(join(dir, name)).isDirectory() &&
        existsSync(join(dir, name, "Cargo.toml"))
      );
    } catch {
      return false;
    }
  });
}

export function resolveProgramName(cwd: string, toml: string): string {
  const unique = [...new Set(parseProgramNamesFromToml(toml))];
  if (unique.length === 1) return unique[0];
  if (unique.length > 1) {
    throw new Error(
      `Multiple programs in Anchor.toml (${unique.join(", ")}). Multi-program deploy is not supported yet.`,
    );
  }
  const dirs = programDirs(cwd);
  if (dirs.length === 1) return dirs[0];
  if (dirs.length > 1) {
    throw new Error(
      `Multiple programs under programs/ (${dirs.join(", ")}). Multi-program deploy is not supported yet.`,
    );
  }
  throw new Error(
    "Could not find a program name in Anchor.toml (expected [programs.<cluster>] entries).",
  );
}

/**
 * Resolve the Anchor project root from a starting directory.
 *
 * Returns the directory that actually contains `Anchor.toml`: either `cwd`
 * itself, or a nested `cwd/anchor` (the layout used by this repo). Returns
 * null when neither exists, so callers can emit their own friendly error.
 *
 * Shared by `bake deploy`, `bake audit`, and anything else that needs to find
 * the program root without duplicating the detection logic.
 */
export function resolveAnchorProjectRoot(cwd = process.cwd()): string | null {
  if (existsSync(join(cwd, ANCHOR_TOML))) return cwd;
  const nested = join(cwd, "anchor");
  if (existsSync(join(nested, ANCHOR_TOML))) return nested;
  return null;
}

/**
 * Resolves the program keypair generated by an Anchor project.
 * Returns null when cwd is not an Anchor project root.
 */
export function resolveProgramIdFromAnchorProject(
  cwd = process.cwd(),
): PublicKey | null {
  const tomlPath = join(cwd, ANCHOR_TOML);
  if (!existsSync(tomlPath)) return null;

  const programName = resolveProgramName(cwd, readFileSync(tomlPath, "utf-8"));
  const keypairPath = join(
    cwd,
    "target",
    "deploy",
    `${programName}-keypair.json`,
  );
  if (!existsSync(keypairPath)) {
    throw new Error(`Program keypair not found at ${keypairPath}.`);
  }

  const raw: unknown = JSON.parse(readFileSync(keypairPath, "utf-8"));
  if (!Array.isArray(raw) || !raw.every((n) => typeof n === "number")) {
    throw new Error(`Program keypair at ${keypairPath} is not a JSON array of numbers.`);
  }
  return Keypair.fromSecretKey(Uint8Array.from(raw as number[])).publicKey;
}
